[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    'forge-std=/Users/lipengyi/sol/libs/forge-std',
    '@openzeppelin/contracts=/Users/lipengyi/sol/libs/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=/Users/lipengyi/sol/libs/openzeppelin-contracts-upgradeable/contracts',
]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
