[profile.default]
# solc_version = "0.6.2"
src = "src"
out = "out"
libs = ["lib"]
evm_version = "london"
fs_permissions = [{ access = "read-write", path = "./output"}]
remappings = [
    'forge-std=lib/forge-std/src',
    '@v2-core=lib/v2-core/contracts',
    '@v2-periphery=lib/v2-periphery/contracts',
    '@openzeppelin/contracts=/Users/lipengyi/sol/libs/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=/Users/lipengyi/sol/libs/openzeppelin-contracts-upgradeable/contracts',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
