[profile.default]
solc = "0.8.25" 
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    '@openzeppelin/contracts=lib/openzeppelin-contracts/contracts',
    '@openzeppelin/contracts-upgradeable=lib/openzeppelin-contracts-upgradeable/contracts',
    '@openzeppelin/foundry-upgrades=lib/openzeppelin-foundry-upgrades/src',
]
build_info = true
extra_output = ["storageLayout"]

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/tDueggKqOUmeeBuLCCQhpvnWnhnsI3pn"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
